routedbits/dn42-peers

- .github/workflows/lint.yml
- .github/workflows/pull_request.yml
- .github/workflows/validate.yml
- requirements.txt
- validate_config.py
Add simple script and GitHub action to validate peer configurations during the pull request cycle.
Resolves #3
> Add peer configuration validation workflow

- routers/router.dal1.yml
- routers/router.fra1.yml
- routers/router.tyo1.yml
Add JK-NETWORK (AS4242422717) in Dallas, Frankfurt and Tokyo
> add: JK-NETWORK (dal, fra, tyo)

- routers/router.sea1.yml
Add Highdef AS4242421080 to Seattle 
Corresponding PR in peer's repo: https://github.com/jlu5/ansible-dn42/pull/14
> chore: add Highdef AS4242421080 to Seattle

- routers/router.dal1.yml
Update Onvox peering to use DNS name.
> chore: update ONVOX peering to use DNS name

- .github/workflows/dispatch_config.yml
This PR attempts to fix a syntax issue found in the limiter workflow. Unfortunately this can only be tested once merged.
> fix: dispatch limit

- routers/router.ams1.yml
- routers/router.fra1.yml
Peering requests from Google Form
> chore: Add AS4242420129 peerings in AMS + FRA

- routers/router.ewr1.yml
From Google Form
Add EXABYTE (AS4242423340) peering to EWR1
> chore(ewr): add EXABYTE (AS4242423340) peering

- routers/router.ewr1.yml
Update peering details on Newark router as requested by user.
> Update EXABYTE-NJ on router.ewr1.yml

- routers/router.tor1.yml
> chore: add BOOTL0ADER AS4242421838 peering in Toronto

- routers/router.fnc1.yml
> chore: add LEMONRFX (AS4242421320) peering in FNC1

- routers/router.lon1.yml
> chore: add AS4242420722 HT1608 Peering in LON1

- routers/router.fra1.yml
> feat: add REJSIK FRA1 peering

- routers/router.atl1.yml
- routers/router.chi1.yml
- routers/router.dal1.yml
- routers/router.fnc1.yml
- routers/router.fra1.yml
- routers/router.sea1.yml
- routers/router.sin1.yml
- routers/router.syd1.yml
- routers/router.tor1.yml
- routers/router.tyo1.yml
Migrate to using DNS remote addresses instead of IP now that the logic is fixed
> refactor: move HIGHDEF peerings to use DNS

- routers/router.chi1.yml
- routers/router.dal1.yml
- routers/router.fra1.yml
- routers/router.iad1.yml
- routers/router.sin1.yml
- routers/router.tyo1.yml
Use DNS for Tech9 peerings instead of IPs
> refactor: set Tech9 peerings to use DNS

- routers/router.dal1.yml
- routers/router.fra1.yml
- routers/router.tyo1.yml
Use DNS instead of hardcoded IPs
> refactor: use DNS for JK-NETWORK peerings

- routers/router.ams1.yml
- routers/router.atl1.yml
- routers/router.sin1.yml
> feat: Add VENTILAAR AS4242422246 peerings (AMS1, ATL1, SIN1)

- routers/router.par1.yml
> feat: Add JCAHILL (AS4242422840) peering in Paris (PAR1)

- routers/router.mia1.yml
Still learning about extended next hop. Disabling for now. Also changing endpoint port for my maintainability.
> Update peering - no Extended Next Hop

- routers/router.atl1.yml
- routers/router.chi1.yml
> chore: add RADIANEXUS peerings in CHI1 and ATL1

- routers/router.tor1.yml
Submission from Google Form -- does not currently resolve
> feat: add TOZTECH peering in Toronto

- routers/router.syd1.yml
> feat: JACK-DN42 AS4242422971 Sydney

- routers/router.gru1.yml
> feat: add GUFE32 AS4242420790 peering in GRU1

- routers/router.ams1.yml
https://github.com/jlu5/ansible-dn42/pull/20
> chore(ams1): add Highdef AS4242421080 peering in AMS1

- routers/router.ams1.yml
> chore(ams1): add H3XNET-RED-NL AS4242422592 peering in AMS1

- routers/router.mum1.yml
Add AS4242422174 / STRYKAR-MUM to router.mum1
Replaces / closes https://github.com/routedbits/dn42-peers/pull/62
> AS4242422174 / STRYKAR-MUM to router.mum1

- routers/router.gru1.yml
Add `sao.peer.highdef.network` to `router.gru1` by request via Google Form submission
> gru1: add HIGHDEF-GRU

- routers/router.tyo1.yml
Add peering requested via form for AS4242421772 on `router.tyo1`
> feat(tyo1): add REX-TYO1

- routers/router.lon1.yml
- routers/router.sin1.yml
> chore: add AS4242421604 peerings to LON1 + SIN1

- routers/router.atl1.yml
> chore: AS4242420662 Peering in ATL1

- routers/router.sto1.yml
Hi!
I have had some issues with my node and saw that it had been offline long enough for you to understandably remove our peering.
> add ALEMAL (AS4242421525) peering in Stockholm STO1 

- routers/router.iad1.yml
Migrate peer YZGUY-IAD1 to dynamic peer
> chore(router.iad1): set YZGUY as dynamic peer

- routers/router.mad1.yml
> chore(router.mad1): add DP-NETWORKS peering

- routers/router.ewr1.yml
Added STARSTORM-NYC1. I'm a bit new, although I added myself to the registry 2 years ago. Why did take this long? It's complicated. I had issues back then I couldn't resolve and I started working on something else, and just took this long to try again. Thank you for the opportunity to peer with your Newark server.
> Add STARSTORM-NYC1

- routers/router.mad1.yml
Added ARFNET peer. Took a while to figure out the wireguard config.
> Add ARFNET peer

- routers/router.ams1.yml
Correct the custom ULA IP address assignment for MARSHAL-AS
> chore(ams1): correct MARSHAL IPs

- routers/router.syd1.yml
> chore(syd1): add MWD2-SYD1 AS4242420002 peering

- routers/router.atl1.yml
Cleanup SC-DUR due to inactivity
> chore: clean SC-DUR due to inactivity

- routers/router.dal1.yml
> chore(dal1): add DGZMN AS4242422724 peering to DAL1

- routers/router.dal1.yml
Migrate ONVOX peer to use dynamic wireguard tunnel
> chore(dal1): move ONVOX-HOU1 to be a dynamic wireguard

- routers/router.mum1.yml
Reverts routedbits/dn42-peers#95
https://github.com/routedbits/dn42-peers/pull/63
/cc @Strykar
> Revert "chore: clean up STRYLAR-MUM1 peer for inactivity"

- registry.py
- requirements.txt
- validate_config.py
#104 
* Small wrapper client for the DN42 Registry Explorer API
* Use client to validate the provided ASN against the API
> feat: use DN42 registry for ASN validation

- routers/router.mil1.yml
Redid config from scratch and PR.
Due to specific configuration can't do multiprotocol BGP session right now, hopefully will be able soon.
WG is configured, should come up when accepted. BGP session will be enabled when up.
> Add AS215751 peering at MIL1

- routers/router.par1.yml
> chore(par1): add SNAILZ AS4242420284 peering

- routers/router.gru1.yml
> chore: add PATERNOT AS4242423073 to GRU1

- routers/router.iad1.yml
> chore(iad1): update YZGUY-IAD link-local

- routers/router.iad1.yml
> chore(iad1): correct YZGUY IAD1 link local

- routers/router.ams1.yml
- routers/router.chi1.yml
- routers/router.ewr1.yml
- routers/router.fra1.yml
- routers/router.lax1.yml
- routers/router.lon1.yml
- routers/router.mia1.yml
- routers/router.par1.yml
- routers/router.sea1.yml
- routers/router.sin1.yml
- routers/router.sto1.yml
- routers/router.syd1.yml
- routers/router.tor1.yml
- routers/router.tyo1.yml
Z-Side PR: https://github.com/Colbyjdx/dn42-ansible/pull/1 (may want to wait until this is merged)
> chore: add various COLBY AS4242422558 peerings

- routers/router.fra1.yml
> chore(fra1): Add AS4242421882 XENO peering

- routers/router.sea1.yml
> chore(sea1): add AS4242420566 peering CDUBS

- routers/router.fra1.yml
> chore(fra1): Add AS4242420566 CDUBS peering

- routers/router.sea1.yml
> refactor(sea1): change CDUBS-SEA1 peering to MP-BGP w/ extended next hop

- routers/router.lon1.yml
> Add AS4242420566 peering at LON1

- routers/router.mil1.yml
- routers/router.syd1.yml
Update AS4242421815 peering info at SYD1
Add AS4242421815 peering at MIL1
> Update AS4242421815 peering info at SYD1 & Add AS4242421815 peering at MIL1

- routers/router.sea1.yml
Add peering via google form submission
> peer(sea1): add MIKEHU44 peering

- routers/router.ams1.yml
Add Google Form requested peering to `router.ams1`.
> peer(ams1): add OLDSCHOOL-AMS peering

- routers/router.lax1.yml
> chore(lax1): add AS4242420358 peering

- routers/router.gru1.yml
> chore: Add AS4242422608 SLIRYA peering at GRU1

- routers/router.gru1.yml
Follow up to #155, user would prefer separate IPv4 and IPv6 sessions.
cc @slirya
> refactor: change AS4242422608 GRU1 peering to separate IPv4/IPv6

- interactive.py
- routers/router.mum1.yml
Submission from Google form
Closes #163
> chore(mum1): Add CDUBS AS4242420566 peering

- routers/router.ams1.yml
Peer has been unresolvable for almost a week, removing.
> chore(ams1): clean up PIVIPI-AMS AS4242420129

- routers/router.fra1.yml
- routers/router.lon1.yml
- routers/router.scl1.yml
- routers/router.sin1.yml
- routers/router.tor1.yml
Add AS4242422016 peerings at FRA1, LON1, SCL1, and SIN1 - update the existing DNS record at TOR1.
> Add multiple AS4242422016 peerings, update TOR1 DNS

- .github/templates/deploy_started.tmpl
> refactor: mention nodes.json on deploy started PR comment

- routers/router.lon1.yml
> Modify AS4242420566 peering at LON1

- routers/router.dal1.yml
> chore(dal1): Add AS4242420490 peering

- routers/router.sea1.yml
> chore(sea1): Add AS4242423703 FMEPNET

- routers/router.mil1.yml
> Update NETZR DN42 peer

- routers/router.fnc1.yml
- routers/router.fra1.yml
Create peering in:
- FRA
- SFO
> chore(fnc1, fra1): Add peering for TATK Network AS4242423152

- routers/router.ams1.yml
- routers/router.chi1.yml
- routers/router.dal1.yml
- routers/router.fnc1.yml
- routers/router.fra1.yml
- routers/router.gru1.yml
- routers/router.lon1.yml
- routers/router.mad1.yml
- routers/router.mia1.yml
- routers/router.par1.yml
- routers/router.sea1.yml
- routers/router.sin1.yml
- routers/router.sto1.yml
- routers/router.tor1.yml
- routers/router.tyo1.yml
* MARSHALL-AMS1
* RAOULBROUNS-AMS01
* RADIANEXUS-CLE
* DGZMN-DAL
* HIGHDEF-DAL
* NOREINX-SFO
* ANTIBUILDING-DE1
* COLBY-FSN1
* GUFE23-GRU
* HIGHDEF-GRU
* LIBECHO-UK1
* DP-NETWORKS-PT
* HIGHDEF-TPA
* TOMPKEN-SRQ
* GALPHANET
* JCAHILL-PAR01
* MIKEHU44
* HIGHDEF-SGP
* COLBY-HEL1
* COLBY-MTL1
* REX-TYO1
> chore: remove peers inactive >= 30d

- routers/router.mil1.yml
Small update due to need for small infra restructure.
Thanks!
> Peer update

- routers/router.maa1.yml
- routers/router.mum1.yml
hi pls merge so i can peer from my router at home
> Add AS4242422457 peering at MUM1

- routers/router.ams1.yml
- routers/router.lon1.yml
changed ipv4 address for London router
> changed ipv4 address for London router

- routers/router.sea1.yml
Submission from Google form, latency to SEA1 was better than requested TOR1
> chore(sea1): Add AS4242423328 DEBOERDN2000 peering

- routers/router.lon1.yml
Config added to peer AS4242421755 at LON1
> Add AS4242421755 peering at LON1

- routers/router.par1.yml
> chore(par1): AS4242420690 ANGELS peering

- routers/router.sea1.yml
> refactor(sea1): change AS4242423328 DEBOERDN2000 to extended next hop

- routers/router.iad1.yml
Changed IPv4 from 172.23.66.193 to .194
> AS211535 IAD1 update

- routers/router.syd1.yml
> chore(syd1): AS4242421855 IMMIBIS peering

- routers/router.syd1.yml
> chore(syd1): add AS4242422227 PUDUNET

- routers/router.sea1.yml
Requested remote-address update via Email
> chore(sea1): update DEBOERDN2000 remote_address

- routers/router.mil1.yml
I fixed the IPv6 mistake I did earlier, let me know if the code is okay now.
> Re-requesting peering for AS4242423885

- routers/router.par1.yml
Add Google Form requested peering for AS4242420129 to `router.par1`
> feat: add AS4242420129 peering in PAR1

- routers/router.chi1.yml
- routers/router.dal1.yml
- routers/router.fnc1.yml
- routers/router.iad1.yml
- routers/router.lon1.yml
This PR should connect my personal dn42 network's nodes to your network. My end is ready to go and will be deployed shortly.
> Add AS4242422002 peerings

- routers/router.chi1.yml
- routers/router.fra1.yml
- routers/router.iad1.yml
- routers/router.lax1.yml
- routers/router.mum1.yml
- validate_config.py
> feat: ensure peers are always alphabetically sorted

- validate_config.py
Improve Duplicate Address Detection validation on BGP peers.
This fortunately has not been a problem yet. However, I noticed that the error output was too generic to help us quickly determine the problem as it generates an error for every peer in the file:
```
routers/router.syd1.yml:2 ipv6 address must be unique per router
routers/router.syd1.yml:14 ipv6 address must be unique per router
routers/router.syd1.yml:26 ipv6 address must be unique per router
routers/router.syd1.yml:38 ipv6 address must be unique per router
routers/router.syd1.yml:50 ipv6 address must be unique per router
routers/router.syd1.yml:62 ipv6 address must be unique per router
routers/router.syd1.yml:74 ipv6 address must be unique per router
routers/router.syd1.yml:87 ipv6 address must be unique per router …
```
> chore: improve duplicate address detection

- routers/router.sto1.yml
> chore(sto1): add PIVIPI AS4242420129

- routers/router.sin1.yml
Address doesn't resolve, removing added in #153 
@moechs Feel free to add your information again when you have a remote address that resolves to something
> chore(sin1): remove MOECHS-HK01 for remote_address non-resolution

- routers/router.mil1.yml
> feat(mil1): add DAV26

- routers/router.chi1.yml
- routers/router.fra1.yml
- routers/router.tyo1.yml
> Add AS4242420202 peering at CHI1, FRA1, TYO11

- routers/router.dal1.yml
> Add AS4242420202 peering at DAL1

- registry.py
Simple methods to just get data about a person from DN42 explorer, especially helpful for getting email/contact info
> feat: add persons/person methods to registry client

- .github/workflows/prune_peers.yml
Improve PR message when using action to prune invalid peers
> ci(prune): improve prune report

- .github/workflows/prune_peers.yml
Another attempt at the auto-pruning workflow with a decent PR message.
> ci: fix prune workflow [skip ci]

- .github/workflows/prune_peers.yml
Another attempt to achieve the desired result with this workflow.
Fixed syntax error in last attempt.
> ci: fix peer pruning workflow [skip ci]

- .github/workflows/prune_peers.yml
- .gitignore
Attempt to use a file for the PR message body versus a variable.
> ci(prune): use body-file for PR message [skip ci]

- .github/workflows/prune_peers.yml
Fix incorrect file reference in prune workflow.
> ci(prune): fix report file reference

- .github/workflows/prune_peers.yml
- .gitignore
One last attempt at fixing the report
> ci: fix prune report [skip ci]

- routers/router.sea1.yml
- routers/router.sin1.yml
Adding peerings with my uswest01 and ap01 nodes to your Seattle and Singapore nodes.
> New peerings with AS4242420401

- routers/router.ewr1.yml
- routers/router.fnc1.yml
- routers/router.lon1.yml
- add ny-czy-1/ewr1 peering
- update endpoint for fre-myb-1 and uk-myb-2
> AS4242421495: update

- routers/router.ewr1.yml
> Add peering for AS4242420202 to EWR1

- routers/router.ewr1.yml
- routers/router.fnc1.yml
- routers/router.lon1.yml
- routers/router.mia1.yml
- add peering mia-czy-1 <> router.mia1
- update Wireguard port and public key to my new standard settings
- enable IPv4 channel
- update YAML session names to match my node names
> AS4242421495: updates

- routers/router.fra1.yml
- routers/router.lax1.yml
- routers/router.scl1.yml
- routers/router.sin1.yml
- routers/router.tyo1.yml
Add new peer iEdon via their automated peering service for the following locations:
- fra1
- lax1
- scl1
- sin1
- tyo1
> feat: add iEdon peerings

- routers/router.ewr1.yml
- routers/router.fra1.yml
- routers/router.iad1.yml
- routers/router.lax1.yml
- routers/router.lon1.yml
- routers/router.sto1.yml
Add Burble AS4242422601 peerings to EWR1,FRA1,IAD1,LAX1,LON1,STO1
> chore: add Burble AS4242422601 peerings to EWR1,FRA1,IAD1,LAX1,LON1,STO1
