validate_config.py
Resolves #2 by ensuring that all BGP neighbors have unique addresses per router.
=> add ipv4/ipv6 neighbor address uniqueness check

README.md, requirements.txt, test_validate_config.py, validate_config.py
Adds support for `remote_address` as a FQDN and update unit tests.
Since the upstream Ansible repo has been updated to resolve DNS names we can now allow peers to specify a FQDN as their endpoint instead of an IPv4/IPv6 address if they wish.
While an IP is still written to the end result configuration (limitation of our platform) they will get updated eventually when Ansible runs again to reconcile the configuration. This should be sufficient enough for this use case. Otherwise future 'road-warrior' WireGuard configuration could better support more dynamically changing peers.
=> feat: add support for peer remote_address as a DNS name

.github/workflows/dispatch_config.yml
Update the merge workflow to trigger when the pull request is closed versus a merge to main. This will ensure we still have a reference to the pull request ID required to interrogate which routers have changed, which allows us to appropriately scope updates the correct routers.
=> fix: set trigger to when pull request is closed

.github/workflows/dispatch_config.yml
Restrict the dispatch job to only when a limit is set. If there are no detected changes, do not dispatch a job.
=> fix: only continue dispatch when ansible limit is set

routers/router.dal1.yml
Test changing onvox back to an IP to validate automatic router deployment.
=> chore: update onvox to test router deployment

routers/router.ams1.yml
https://github.com/routedbits/ansible-routedbits-vyos/issues/212
Seems that the DNS used for the PIVIPI-AMS peering does not have an IPv6 address (which we prefer), but is somehow misconfigured in that there is a record created, but no answer.
This is a format error to Bind, but returns a NOERROR from Cloudflare (1.1.1.1)
We will just use the IPv4 address instead of the DNS for this peer.
=> fix: use IPv4 address for AMS1 PIVIPI peering

routers/router.ewr1.yml, routers/router.fnc1.yml, routers/router.fra1.yml, routers/router.lon1.yml, routers/router.par1.yml
Migrate Kioubit peerings to use DNS instead of IPs directly. Looks like the IP changed for the EWR1 peering
=> refactor: migrate Kioubit peerings to use DNS

routers/router.ewr1.yml, routers/router.lon1.yml
Revert EWR1 + LON1 Kioubit peerings to IP, the DNS resolving logic isn't working correct in some (all?) instances so it's not continuing on to resolve the IPv4 instead.
Will revert these IPs in the meantime to keep deploys working while investigating a fix.
=> refactor: set Kioubit LON1,EWR1 address to IP

routers/router.tor1.yml
Remove /64 from IP on BOOTL0ADER Toronto peering
=> fix: remove CIDR from BOOTL0ADER Toronto peering

routers/router.ams1.yml
Reverts routedbits/dn42-peers#23
Use DNS for this instead of IP now that we have fixed the DNS lookup logic
=> Revert "fix: use IPv4 address for AMS1 PIVIPI peering"

routers/router.ewr1.yml, routers/router.lon1.yml
Reverts routedbits/dn42-peers#29
We have fixed the DNS lookup logic so we can re-revert this to use DNS again.
=> Revert "refactor: set Kioubit LON1,EWR1 address to IP"

routers/router.ewr1.yml, routers/router.fra1.yml, routers/router.lax1.yml, routers/router.sin1.yml, routers/router.tyo1.yml
Remove prefix notation from peering configuration. This is likely getting confused for special edge cases where `local_ipX` is required to specify an different peering subnet.
An additional fix in the automation repo prevents this from being an issue in the future, however, this is to promote consistency.
=> fix(SERNET): remove prefix notation from peering address

.github/dependabot.yml, test_validate_config.py, validate_config.py
This PR allows the configuration of dynamic wireguard peers by leaving out `remote_address` and `remote_port` under the WireGuard configuration:
```yaml
- name: TEST-PEER
asn: 4242420000
ipv6: fe80::1
multiprotocol: true
extended_nexthop: true
sessions: [ipv6]
wireguard:
public_key: 1GBNudioxk6PFrrZm3hDIAOoQvzlurR6buMFv6ZEnkc=
```
=> feat: allow dynamic wireguard peers

README.md, interactive.py, routers/router.ams1.yml, routers/router.atl1.yml, routers/router.chi1.yml, routers/router.dal1.yml, routers/router.ewr1.yml, routers/router.fnc1.yml, routers/router.fra1.yml, routers/router.gru1.yml, routers/router.iad1.yml, routers/router.lax1.yml, routers/router.lon1.yml, routers/router.mad1.yml, routers/router.mia1.yml, routers/router.mum1.yml, routers/router.par1.yml, routers/router.sea1.yml, routers/router.sin1.yml, routers/router.sto1.yml, routers/router.syd1.yml, routers/router.tor1.yml, routers/router.tyo1.yml, validate_config.py
Addresses #59
Interactive script for new peerings
```
-> ./interactive.py
What router would you like to peer at?
1. router.ams1  	8. router.fra1   	15. router.mia1  	22. router.sto1
2. router.atl1  	9. router.gru1   	16. router.mil1  	23. router.syd1
3. router.cgk1  	10. router.iad1  	17. router.mum1  	24. router.tor1
4. router.chi1  	11. router.lax1  	18. router.osa1  	25. router.tyo1
5. router.dal1  	12. router.lon1  	19. router.par1
6. router.ewr1  	13. router.maa1  	20. router.sea1
7. router.fnc1  	14. router.mad1  	21. router.sin1
Selection: 7
Peer Name: YZGUY-FNC
DN42 ASN: 4242421669
Which BGP peering type are you requesting?
1. Multi-protocol (IPv4 and IPv6) with Extended Nexthop capability (preferred)
2. Multi-protocol (IPv4 and IPv6)
3. IPv4 and IPv6 (separate sessions)
4. IPv4 …
```
=> feat: add interactive script for new peerings

routers/router.ams1.yml, validate_config.py
Use IPv6 ULA on p2p wireguard link for MARSHAL-AS.
=> chore(ams1): update MARSHAL-AS peering address

.github/templates/deploy_started.tmpl, .github/workflows/deploy_started.yml, routers/router.iad1.yml
=> feat: comment deploy completion on merged pull requests

routers/router.ewr1.yml
Peer STARSTORM-NYC1 on `router.ewr1` was discovered not to be sending extended nexthop capability and causing route flap issues between peers.
```
BGP neighbor is fe80::2926, remote AS 4242420275, local AS 4242420207, external link
Local Role: undefined
Remote Role: undefined
Description: STARSTORM-NYC1
[...]
Neighbor capabilities:
4 Byte AS: advertised and received
Extended Message: advertised and received
AddPath:
IPv4 Unicast: RX advertised
IPv6 Unicast: RX advertised
Extended nexthop: advertised
[...]
```
This PR corrects the session to insert a static IPv4 route for their tunnel endpoint and use a single IPv6 session for both IPv4 and IPv6 address-families without using extended-nexthop.
=> fix(starstorm-nyc1): fix incorrect extended nexthop capability

routers/router.dal1.yml
HIGHDEF no longer has a MCI endpoint, our peering was moved to their DAL endpoint (https://github.com/jlu5/ansible-dn42/blob/1ca3875599ed181cf897fa1b16b612931c5df369/roles/config-wireguard/config/dal.yml#L39-L44)
=> chore(dal1): use HIGHDEF AS4242421080 DAL endpoint

routers/router.atl1.yml, routers/router.mia1.yml
Noticed earlier that some of the highdef peerings don't go to where they originally went, eg ATL1 to ATL.
The ATL1 peering now goes to their Tampa (TPA) node
```
-> dig atl.peer.highdef.network +short
tpa.peer.highdef.network.
158.51.125.4
```
Looking at the latency between ATL1 and TPA, and MIA1 and TPA it's much better going to MIA1 (16ms vs 8ms)
ATL1 <> TPA
```
yzguy@router.atl1:~$ ping tpa.peer.highdef.network count 1
PING tpa.peer.highdef.network(2606:65c0:20:97:ae8:3d00:92c9:abdf.hostodo.com (2606:65c0:20:97:ae8:3d00:92c9:abdf)) 56 data bytes
64 bytes from 2606:65c0:20:97:ae8:3d00:92c9:abdf.hostodo.com (2606:65c0:20:97:ae8:3d00:92c9:abdf): icmp_seq=1 ttl=53 time=16.0 ms
--- tpa.peer.highdef.network ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt …
```
=> chore: migrate HIGHDEF peering from ATL1 to MIA1

.github/workflows/dispatch_config.yml
When users submit a PR from a fork, we review + merge. However the Actions fail because they don't have permissions to secrets, etc because the use of `on: pull_request` is read-only, and therefore cannot make changes to the upstream repo
[pull_request_target](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target) was created to address this, but has some security implications, as it has access to secrets and can make changes to the upstream
I believe the security concerns are mitigated based on:
* The action will run in the context of the base of the pull request rather than the context of the merge commit.
* It only runs after a pull request is closed and it was a merge (which can only be done by us after reviewing)
* It only runs on …
=> feat: dispatch config on pull_request_target

routers/router.chi1.yml, routers/router.fra1.yml, routers/router.lax1.yml, routers/router.mia1.yml, routers/router.par1.yml, routers/router.sin1.yml, routers/router.sto1.yml, routers/router.tor1.yml, routers/router.tyo1.yml
It was [mentioned](https://github.com/Colbyjdx/dn42-ansible/pull/1#issuecomment-2103606066) that some nodes are not IPv4 capable, therefore we should clean up the MP-BGP w/ ext-nh config for these peerings
=> refactor: Remove MP-BGP ext-nh on some COLBY AS4242422558

interactive.py, registry.py
* Add simple `--registry` flag to enable outputting data from the registry after data is entered.
* After getting the ASN from the user, do a quick API call to to the registry to get data about the ASN and output it
```
-> python interactive.py --registry
What router would you like to peer at?
1. router.ams1  	8. router.fra1   	15. router.mia1  	22. router.sto1
2. router.atl1  	9. router.gru1   	16. router.mil1  	23. router.syd1
3. router.cgk1  	10. router.iad1  	17. router.mum1  	24. router.tor1
4. router.chi1  	11. router.lax1  	18. router.osa1  	25. router.tyo1
5. router.dal1  	12. router.lon1  	19. router.par1
6. router.ewr1  	13. router.maa1  	20. router.sea1
7. router.fnc1  	14. router.mad1  	21. router.sin1
Selection: 1
DN42 ASN: 4242421882
AS-NAME:	XENO-AS
Description:	Xenot AS …
```
=> feat: output ASN info from registry in interactive

interactive.py
Just some testing after and ran into an error because a peer didn't have a 'description' field in their ASN registry entry
```
DN42 ASN: 4242422246
Traceback (most recent call last):
File "/workspaces/dn42-peers/interactive.py", line 268, in <module>
main(args)
File "/workspaces/dn42-peers/interactive.py", line 115, in main
'Description': r_asn['descr']
~~~~~^^^^^^^^^
```
Quick just to look for if the key exists in the response and provide a default if not
=> fix: handle missing asn fields from registry

.devcontainer/devcontainer.json
https://medium.com/marvelous-mlops/how-to-start-with-dev-containers-1e92bf0e0f78
Add a basic devcontainer configuration that uses 3.12 Python image, and will install all the requirements needed for the registry automatically
This allows us/users to just launch an dev environment easily without installing anything to our system
=> feat: add basic devcontainer configuration

routers/router.ams1.yml
Remove peer `H3XNET-RED-NL` (AS 4242422592) from `router.ams1`
Their DNS record is `NXDOMAIN` and the peer has been down for >2 weeks:
```
$ show bgp vrf DN42 neighbors fe80::2592 | grep -A 1 Connections
Connections established 0; dropped 0
Last reset 02w0d13h,   Waiting for peer OPEN (n/a)
```
=> chore: remove H3XNET-RED-NL

routers/router.fra1.yml
Remove `PIVIPI-FRA` from `router.fra1`. This peer's DNS record is failing and has been down for over 3 weeks.
=> chore(router.fra1): remove PIVIPI-FRA (failing DNS records)

Makefile, README.md
Add simple Makefile to simplify use for peering requests.
Now all a user will need to do is clone the repository and type `make peering` or just `make` to have all Python dependencies installed and prompted for peering information.
=> feat: add simple Makefile

Makefile
The Makefile `peering` task was not switching to the Python virtual environment before running. 
This updates the task to activate the python environment before running the script.
=> fix: ensure makefile task switches to venv before execution

routers/router.lon1.yml, routers/router.sin1.yml
Quick re-sorting of peers to be in alphabetical order
```python
#!/usr/bin/env python
import yaml
from interactive import load_router_peers, save_router_peers
from pathlib import Path
from os import listdir
routers = sorted([Path(router).stem for router in listdir('routers')])
for router in routers:
peers = load_router_peers(router)
save_router_peers(router, peers)
```
=> chore: re-sort peers alphabetically

Makefile
This PR adds aMakefile target to kick off the validation process:
`make validate`
=> feat: add 'validate' target to Makefile [skip ci]

interactive.py
Noticed when submitting #155 
When selecting `Multi-protocol (IPv4 and IPv6)`, the previous logic was to request what address family the BGP session would be and depending on that then ask the user their tunnel address for that address family only. In the case of `Multi-protocol (IPv4 and IPv6)`, the session will happen over one of the address family, but we still need both the IPv4 and IPv6 tunnel addresses from the user
Previous behavior
```
Which BGP peering type are you requesting?
1. Multi-protocol (IPv4 and IPv6) with Extended Nexthop capability (preferred)
2. Multi-protocol (IPv4 and IPv6)
3. IPv4 and IPv6 (separate sessions)
4. IPv4 ONLY
5. IPv6 ONLY
Selection: 2
Session Address Family (ipv4, ipv6): ipv6
IPv6 tunnel address (Link-local preferred, /64 assumed unless specified): …
```
=> fix: request IPv4 and IPv6 tunnel address when using MP-BGP

interactive.py, routedbits.py
Use the https://dn42.routedbits.com/nodes.json endpoint to get extra to make the user experience better, in particular we use the City name instead of the router name when displaying the options
```
-> python interactive.py
Which RoutedBits endpoint would you like to peer with?
1. Amsterdam, NL (AMS1)         	14. Miami, FL, US (MIA1)
2. Ashburn, VA, US (IAD1)       	15. Milan, IT (MIL1)
3. Atlanta, GA, US (ATL1)       	16. Mumbai, IN (MUM1)
4. Chennai, IN (MAA1)           	17. Newark, NJ, US (EWR1)
5. Chicago, IL, US (CHI1)       	18. Osaka, JP (OSA1)
6. Dallas, TX, US (DAL1)        	19. Paris, FR (PAR1)
7. Frankfurt, DE (FRA1)         	20. Sao Paulo, BR (GRU1)
8. Fremont, CA, US (FNC1)       	21. Seattle, WA, US (SEA1)
9. Jakarta, ID (CGK1)           	22. Singapore, SG (SIN1)
10. …
```
=> feat: use data from routedbits nodes.json in interactive

routers/router.sea1.yml, routers/router.sin1.yml, test_validate_config.py, validate_config.py
Closes #161
We now have IPv4 only nodes which means we cannot accept any wireguard endpoint from a peer that is an IPv6 address or resolves to an IPv6 address.
This change adds additional validation to ensure that only an IPv4 address or a valid A record will be allowed on a router that is IPv4 only 
Random
* Re-sorted the peers alphabetically
=> feat: handle wireguard remote_address validation for IPv4 only node

routers/router.syd1.yml
`MWD-SYD1` is not sending extended-next hop information for IPv4 routes:
```
BGP neighbor is fe80::2:0, remote AS 4242420002, local AS 4242420207, external link
Local Role: undefined
Remote Role: undefined
Description: MWD2-SYD1
[...]
Extended nexthop: advertised  #<-- advertised but not received
[...]
```
FRR is installing an IPv4 route advertised from this neighbor which causes it to become recursive and inactive which is triggering a flapping event on DN42:
```
$ show ip route vrf DN42 172.23.227.0/24
Routing entry for 172.23.227.0/24
Known via "bgp", distance 20, metric 0, vrf DN42
Last update 00:00:00 ago
172.23.227.1 inactive, weight 1
$ show ip route vrf DN42 172.23.227.0/24
Routing entry for 172.23.227.0/24
Known via "bgp", distance 20, metric 0, vrf DN42, best
Last update …
```
=> fix: MWD2-SYD1 does not appear to be sending extended next-hop

routers/router.mil1.yml
Submission from Google form.
User originally selected London (LON1, 26ms) but have chosen to setup on Milan (MIL1, 9ms)
=> chore(mil1): Add AS4242422114 BAO

routers/router.ams1.yml, routers/router.fra1.yml
Submissions from Google Form
#131 #165 were the relevant PRs to remove the peerings due to no longer resolving DNS
=> chore: Add AS4242420129 PIVIPI to FRA1/AMS1

routers/router.ewr1.yml, routers/router.fra1.yml, routers/router.lon1.yml
Mailing list email
AS424243088 will shutdown the following nodes
Node name: nyc1 Location:New York City Expiration Date:11/20/2024
Node name: lon1 Location:London Expiration Date:11/26/2024
Node name: fra1 Location:Frankfurt Expiration Date:11/30/2024
Node name: ams1 Location:Amsterdam Expiration Date:21/20/2024
DN42: AS4242423088 Clearnet: AS7721
=> chore: unpeer with decomm'd SUNNET nodes

routers/router.dal1.yml
Add `local_ipv6` to support BGP peering over ULA addressing.
=> chore(BSDROCKER): add local IPv6 for ULA support

routers/router.sin1.yml
Unfortunately this peer's DNS record: `hk1.vm.libecho.top` has stopped resolving for multiple days now.
The wireguard tunnel and BGP peering appears to be up so I have set the `remote-address` to the current wireguard peer's remote address.
=> chore(sin1): update LIBECHO-HK1 remote-address

routers/router.mil1.yml
Reverts routedbits/dn42-peers#233
Sorry - I should have caught this. You cannot do multiprotocol sessions over IPv4 only.
It should look like this instead:
```yaml
- name: NICHOLASSYSTEMS
asn: 4242423885
ipv4: 172.22.98.32
ipv6: fdf6:f32e:9196::/48
multiprotocol: true
sessions:
- ipv6
wireguard:
remote_address: 37.202.207.206
remote_port: 53885
public_key: Bf0mpBjtlK8fI0UNFJEBBD588EbZluvt7gJuhvAOsU4=
```
=> Revert "Add AS4242423885 peering at MIL1"

routers/router.gru1.yml, test_validate_config.py, validate_config.py
Add check to ensure `ipv4` BGP sessions are not used with `multiprotocol: true`
=> fix(validation): add check for multiprotocol BGP sessions

routers/router.iad1.yml, routers/router.mil1.yml
The following ASNs are no longer present in the DN42 registry:
- AS215751 (PR #106)
- AS211535 (PR #213)
These peers are being removed from the configuration.
=> chore: remove peers with invalid DN42 registry information

routers/router.mil1.yml
Reverts routedbits/dn42-peers#235
Sorry this is still an issue:
```diff
- name: NICHOLASSYSTEMS
asn: 4242423885
ipv4: 172.22.98.32
-   ipv6: fdf6:f32e:9196::/48 <- this has to be a valid IPv6 address used for the BGP peering session. ::0 would be the subnet address
multiprotocol: true
sessions:
- ipv6
wireguard:
remote_address: 37.202.207.206
remote_port: 53885
public_key: Bf0mpBjtlK8fI0UNFJEBBD588EbZluvt7gJuhvAOsU4=
```
Note that the IPv6 configuration here is for your tunnel's IPv6 address, not your DN42 prefix (you should be advertising that over BGP).
=> chore(#235): remove invalid peering configuration

test_validate_config.py, validate_config.py
Add validations to ensure that:
- The peer's IPv4 tunnel address (`ipv4:`) is:
- not the subnet address
- not the broadcast address
- The peer's IPv6 tunnel address (`ipv6:`) is:
- not the subnet address
These validations are gated on subnet sizes greater that 2 addresses. This should exempt `/32` or `/128` specific instances as well as allow for `/31` addressing.
We should probably consider updating these keys to be more descriptive as they have generated some confusion in the past.
=> chore: add tunnel IP address validation

routers/router.sea1.yml
`sea.jvav.tech` no longer resolves and the BGP session with this peer is no longer established
Related #44
=> chore: remove AS4242421350

routers/router.osa1.yml
My domain `cowgl.xyz` has expired and will likely stop working soon, so I've changed my endpoint to another domain I own.
=> change cowgl endpoint

routers/router.lax1.yml
Remove `MOECHS-US01`. DNS has failed to respond for their endpoint for multiple days and their peering is down:
```
IPv4 Unicast Summary:
Neighbor           V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
fe80::1522         4 4242421522         0      7047        0    0    0    never       Active        0 MOECHS-US01
IPv6 Unicast Summary:
Neighbor                V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
fe80::1522              4 4242421522         0      7047        0    0    0    never       Active        0 MOECHS-US01
```
They are welcome to submit another PR to re-request peering in the future.
Related #153
=> chore(lax1): remove MOECHS-US01

routers/router.ewr1.yml, routers/router.fra1.yml, routers/router.lax1.yml
Peer has 3 non-resolvable remote_address, removing
Peer can re-request when they fix it
=> chore: remove SERNET for DNS non-resolution

.github/workflows/prune_peers.yml, prune.py
A simple workflow to prune peers from the repository when they have become invalid.
This first commit sets the PR to only action on manual dispatches. This could become a scheduled job in the future.
=> ci: add invalid peer pruning workflow

.github/workflows/prune_peers.yml
Fix the prune workflow to hopefully produce the desired report.
I was attempting to `tee` the output of the prune script while also saving its output. Now the script will complete, dump its entire output to the log and then attempt to pull the report at the end for the PR.
=> ci: fix prune output

.github/workflows/prune_peers.yml, .github/workflows/pull_request.yml
* Resolved issue with PR message body
* Updated workflow to mark PR as draft
- PRs created by using the `GITHUB_TOKEN` will not trigger checks to run. [See docs](https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#triggering-further-workflow-runs)
- By creating them as draft PR's we should be able to mark them ready for review to trigger the check to then run
=> ci: fix prune PR message [skip ci]

routers/router.sin1.yml
This node has been nothing but trouble since I deployed it, so just deleting it and will submit a new peering request later once I've switched everything to a new provider and can confirm it's more reliable/stable.
=> Remove my problematic ap01 node

test_validate_config.py, tests/fixtures/valid_ext_nh, validate_config.py
Validate peering requests use public IPv4/IPv6 resolved tunnel endpoints for WireGuard tunnels.
=> chore(#294): ensure tunnel endpoints are public

routers/router.ams1.yml
nl-myb-1 doesn't have IPv4 clearnet, so remove peering with IPv4-only router.ams1.
=> router.ams1: remove 4242421495 peering

test_validate_config.py, validate_config.py
* Add ability to validate a single router
* If no router is specified it will continue to validate all routers to preserve previous behavior
```
-> python validate_config.py --router router.ewr1               
Validating peer: CDUBS-NJ... ok 
Validating peer: COLBY-NYC1... ok 
Validating peer: EXABYTE-NJ... ok 
Validating peer: KIOUBIT-US2... ok 
Validating peer: LE-FAY-NY... ok 
Validating peer: LUTOMA-NYC... ok 
Validating peer: SDUBS-TOR... ok 
Validating peer: STARSTORM-NYC1... ok 
Validating peer: STEPNEM-NYC1... ok 
Validating peer: TATK-NYC1... ok 
-> python validate_config.py          
Validating peer: BARAGOON-AMS... ok 
Validating peer: COLBY-AMS1... ok 
Validating peer: HEXXNET-AMS1... ok 
Validating peer: HIGHDEF-AMS... ok 
Validating peer: PIVIPI-NL1... ok 
Validating peer: …
```
=> feat: add ability to validate single router

routers/router.chi1.yml, routers/router.fra1.yml, routers/router.lax1.yml, routers/router.lon1.yml
Add auto-peerings to LARE-MNT at the following locations:
- chi1 - lare-use2
- fra1 - lare-de01
- lax1 - lare-usw1
- lon1 - lare-uk01
They also have Tokyo in close proximity to our tyo1 router, however their site responded with 500 error when configuring that location.
=> add LARE autopeerings

routers/router.lon1.yml
Migrating LON1 to new provider, it is now an Clearnet IPv4-only node, therefore we cannot support IPv6 only nodes
* COLBY-BHX1, AS4242422558 /cc @colbyjdx
* We could move this to a different PoP, maybe AMS1/FRA1/PAR1
* LE-FAY-UK-MYB-2, AS4242421495 /cc @llfw
* We could move this to a different PoP, maybe AMS1/FRA1/PAR1
=> refactor(lon1): remove IPv6 only peers
